services:
    smkg-static:
        image: nginx:latest
        container_name: smkg-static
        restart: unless-stopped
        volumes:
            - ./html:/usr/share/nginx/html
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.smkg-static.rule=Host(`smkg.me`)"
            - "traefik.http.routers.smkg-static.entrypoints=websecure"
            - "traefik.http.routers.smkg-static.tls.certresolver=letsencrypt"
        networks:
            - traefik_proxy
networks:
    traefik_proxy:
        external: true
