version: "3"

# services
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        volumes:
            - .:/usr/share/nginx/html
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.smkg-static.rule=Host(`smkg.me`)"
            - "traefik.http.routers.smkg-static.entrypoints=websecure"
            - "traefik.http.services.smkg-static.loadbalancer.server.port=80"
        networks:
            - traefik_web

# networks
networks:
    traefik_web:
        external: true
