version: "3"

# services
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        volumes:
            - ./:/usr/share/nginx/html
        ports:
            - "80:80"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.smkg-static.rule=Host(`smkg.me`)"
            - "traefik.http.routers.smkg-static.entrypoints=websecure"
        networks:
            - traefik_web

# networks
networks:
    traefik_web:
        external: true
