version: "3"

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        volumes:
            - .:/usr/share/nginx/html
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.smkg-static.rule=Host(`smkg.me`)"
            - "traefik.http.routers.smkg-static.entrypoints=websecure"
            - "traefik.http.routers.smkg-static.tls.certresolver=letsencrypt"
        networks:
            - traefik_proxy

# networks
networks:
    traefik_proxy:
        external: true
